export const paymentMethods = [
  {
    id: 1,
    name: "BTC",
    method: "btc",
    commission: 3,
    address: "1BLLUrH7SLGGF8fzh4HL6CkSA8rB6yVmet",
    qrCodeInstruction: [
      "Send only BTC to this deposit address.",
      "Ensure the network is Bitcoin",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/btc.svg",
  },
  {
    id: 2,
    name: "ETH",
    method: "eth",
    commission: 3,
    address: "0xc918e3201c545edc10fd4fbf275b41743de6f5c1",
    qrCodeInstruction: [
      "Send only ETH to this deposit address.",
      "Ensure the network is Ethereum (ERC20)",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/eth.svg",
  },
  {
    id: 3,
    name: "DOGE",
    method: "doge",
    commission: 3,
    address: "DMf74s2SSoE767QGhdeDwjNZPGgN7SjbuL",
    qrCodeInstruction: [
      "Send only DOGE to this deposit address.",
      "Ensure the network is Dogecoin",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/doge-coin.svg",
  },
  {
    id: 4,
    name: "LTC",
    method: "ltc",
    commission: 3,
    address: "LRhWEhd2rUXuxYBTfjrDHfTaEendEiMczZ",
    qrCodeInstruction: [
      "Send only LTC to this deposit address.",
      "Ensure the network is Litecoin",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/lite-coin.svg",
  },
  {
    id: 5,
    name: "USDC(ERC20)",
    method: "usdc",
    commission: 3,
    address: "0xc918e3201c545edc10fd4fbf275b41743de6f5c1",
    qrCodeInstruction: [
      "Send only USDC to this deposit address.",
      "Ensure the network is USDC(ERC20)",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/usdc.svg",
  },
  {
    id: 6,
    name: "USDT(TRC20)",
    method: "usdt-trc20",
    commission: 3,
    address: "TWzpqySXiyjhVLWoSnQ3yje1akm78RJAaM",
    qrCodeInstruction: [
      "Send only USDT to this deposit address.",
      "Ensure the network is USDT(TRC20)",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/tether.svg",
  },
  {
    id: 7,
    name: "USDT(ERC20)",
    method: "usdt-erc20",
    commission: 3,
    address: "0x67dc33f41c46bff8b615ca48a9d1c03f6bf9b188",
    qrCodeInstruction: [
      "Send only USDT to this deposit address.",
      "Ensure the network is USDT(ERC20)",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/tether.svg",
  },
  {
    id: 8,
    name: "SOL",
    method: "solana",
    commission: 3,
    address: "GgFe7erq9CLZmKtZ3qYwfvX6xi1qUpUpGqRsj56j1aWj",
    qrCodeInstruction: [
      "Send only SOL to this deposit address.",
      "Ensure the network is Solana",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/solana.svg",
  },
  {
    id: 9,
    name: "Perfect Money",
    method: "perfect-money",
    commission: 1,
    address: "U34174248",
    qrCodeInstruction: [
      "Send only Perfect Money to this deposit address.",
      "Ensure the network is Perfect Money",
      "Do not send NFTs to this address",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/perfect-money.svg",
  },
  {
    id: 10,
    name: "Bank Transfer",
    method: "bank-transfer",
    commission: 0,
    address: "",
    qrCodeInstruction: [
      "Send only Perfect Money to this deposit address.",
      "Ensure the network is Perfect Money",
      "Do not send NFTs to this address ",
    ],
    data: {
      bank_name: "Mashreq Bank PSC",
      account_type: "Checking",
      account_number: "019100682176",
      routing_number: "203320101",
      iban: "AE720330000019100682176",
      swift_code: "BOMLAEAD",
      beneficiary_name: "GROWTHNEXT FZC",
      beneficiary_email: "support@fundednext.com",
      beneficiary_address: "AI Robotics Hub – EO – 7, Ajman, UAE",
    },
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/bank-transfer.svg",
  },
  {
    id: 11,
    name: "WebMoney",
    method: "wmz-purse",
    commission: 3,
    address: "Z931204696786",
    qrCodeInstruction: [
      "Send only Web Money to this deposit address.",
      "Ensure the network is Web Money ",
      "Do not send NFTs to this address ",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/wmz-purse.svg",
  },
  {
    id: 12,
    name: "USDC(TRC20)",
    method: "usdctrc20",
    commission: 5,
    address: "TWzpqySXiyjhVLWoSnQ3yje1akm78RJAaM",
    qrCodeInstruction: [
      "Send only USDC to this deposit address.",
      "Ensure the network is USDC(TRC20)",
      "Do not send NFTs to this address",
    ],
    data: null,
    icon: "https://fundednext.fra1.digitaloceanspaces.com/dashboard/usdc.svg",
  },
];
